source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8



baseurl: /blogs
markdown: kramdown 
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile
encoding:  "utf-8"
safe: false
pygments: true
highlighter: pygments
excerpt_separator: "\n\n\n"
paginate: 5